config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        post '/representatives/:representative_id/my_news_item/search' => 'my_news_items#search',
            :as                                                    => :search_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
end

app/models/representative.rb
# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all

  def self.civic_api_to_representative_params(rep_info)
    reps = []

    rep_info.officials.each_with_index do |official, index|
      ocdid_temp = ''
      title_temp = ''

      rep_info.offices.each do |office|
        if office.official_indices.include? index
          title_temp = office.name
          ocdid_temp = office.division_id
        end
      end

      address = official.address ? concatenate_addr(official.address) : ''
      photo_url = official.photo_url || ''

      # check if it already exists
      rep = Representative.find_by(name: official.name)

      if rep.nil?
        rep = Representative.create!({ name: official.name, ocdid: ocdid_temp,
            title: title_temp, address: address, photo: photo_url, party: official.party })
      end

      reps.push(rep)
    end
    reps
  end

  def self.concatenate_addr(addr)
    res = "#{addr[0].line1}, "

    # res += "#{addr[0].line2}, " unless addr[0].line2.nil?
    # res += "#{addr[0].line3}, " unless addr[0].line3.nil?

    res += remove_nil(addr[0].line2) + remove_nil(addr[0].line3)

    res += "#{addr[0].city}, "
    res += "#{addr[0].state} #{addr[0].zip}"
    res
  end

  def self.remove_nil(string)
    string.nil? ? '' : string
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end

  def show
    @representative = Representative.find(params[:id])
    # binding.pry
    @ocdid_state = nil
    state = @representative.ocdid.match(/state:(\w{2})/)
    @ocdid_state = state.captures[0].upcase unless state.nil?

    @default_photo = 'https://twirpz.files.wordpress.com/2015/06/twitter-avi-gender-balanced-figure.png'
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
- if flash[:error].present?
    .d-flex.justify-content-center.mt-3
        .alert.alert-danger.alert-dismissible.fade.show{ role: 'alert' }
            = flash[:error]

.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get do
            .form-group.row
                .col-md-4
                    %label.col-form-label
                        Enter a location:
                .col-md-6
                    = text_field_tag(:address, nil, class: 'form-control')

            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
    .row
        .col-md-8.offset-md-2
            .table-responsive-md.pt-5
                %table.table.table-striped.table-hover#events
                    %caption Table of Representatives
                    %thead.thead-dark
                        %tr
                            %th Name
                            %th Office
                            %th Links
                    %tbody
                        - @representatives.each_with_index do |rep, _index|
                            %tr
                                %td= link_to rep.name, representative_path(rep.id)
                                %td= rep.title
                                %td
                                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                                        %i.fas.fa-newspaper
                                        News Articles

app/views/representatives/show.html.erb
<div class="container">
  <div class="row align-items-start my-5"> 
    <div class="col-3">
      <%= image_tag(!@representative.photo.empty? ? @representative.photo : @default_photo, style: "max-height: 225px; max-width: 180px;", class: "img-thumbnail") %>
    </div>
    
    <div class="col-4">
      <h1><%= @representative.name %></h1>
      <h3 class="mb-3"><%= @representative.title %> </h3>
      <p style=<%= @ocdid_state.nil? ? "display:none" : "display:block" %>>State: <%= @ocdid_state %></p>
      <p>Political Affiliation:
      <span style="color: <%= if @representative.party.include?("Democratic")
          "blue"
        elsif @representative.party.include?("Republican")
          "red"
        end%>">
        <%= @representative.party %>
        </span>
        </p>
    </div>

    <div class="col-3 .offset-md-1">
      <h3>Address:</h3>
      <p><%= @representative.address.empty? ? "No Address Found" : @representative.address %></p>
    </div>
  </div>
  <div>
    <%= link_to 'Back', :back, class: "btn btn-primary"%>
  </div>
</div>